### ISSUE TITLE
Theme Watch - Too many files open for 249 files

### ISSUE THREAD

**Issue by sogko** [Shopify/themekit#116]
Theme watch fails when I have 249 files in the theme folder.

```
2015/12/04 03:19:01 open <..redacted_path...>/templates: too many open files
```

When  I moved out some asset files out (bringing the file count down to 218 files), theme watch works.

I tried to add the assets folder to `ignore_files`, it didn't help though, which is kind of weird. Is my config for ignore_files wrong? 

config.yml
```yml
development:
  access_token: -------
  store: ---
  ignore_files:
    - .gitignore
    - .git/
    - .idea/
    - assets/
  refill_rate: 2
  bucket_size: 40
  concurrency: 2
```

Platform: OSX 10.11.1

Cheers!
