### ISSUE TITLE
ignore_files not respected with download command

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/themekit#126]
I ran `theme download --env=tpa-dec01` with the following config.yml file:

```
tpa-dec01:
  theme_id: 77036487
  access_token: #############
  store:######.myshopify.com
  ignore_files:
    - config/settings_data.json
    - "*.png"
    - "*.jpg"
```

I expected it to not download any png or jpg files, but it downloaded all of them.  Am I missing something, or is this a bug?
