### ISSUE TITLE
Temp(?) file created with tilde (~) at end, throwing error on watch

### ISSUE THREAD

**Issue by mhulse** [Shopify/themekit#162]
First, thanks for this great tool!

Theme Kit v0.3.6

```shell
$ theme watch --dir=theme
Received Update event on templates/gift_card.liquid~
Received Update event on templates/gift_card.liquid
Could not upload templates/gift_card.liquid~:
	"templates/gift_card.liquid~" contains illegal characters
Must have a .liquid file extension
Successfully performed Update operation for file templates/gift_card.liquid to xxxx.myshopify.com
```

There is no `gift_card.liquid~` from what I can see.

I'm new, so, maybe this is a feature (or, more likely, I’m doing it wrong)?

**Comment by brettchalupa** [comment]
@mhulse Files that end in `~` are usually temporary files, potentially created by a text editor. You can configure themekit to ignore those files so that they do not attempt to get uploaded to the shop. Here is an example config:

```
production:
  store: example.myshopify.com
  password: test
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "*.swp"
    - "*~"
    - "config/settings_data.json"
```

The `ignore_files` option is set to ignore swap files and temporary editor files, like ones that end with `~`.
