### ISSUE TITLE
Error version 0.4.4

### ISSUE THREAD

**Issue by KaBrau08** [Shopify/themekit#220]
After install the latest version of Theme Kit(0.4.4) i can't do anything. The theme watch command its disabled and now when i download a theme returns empty files. I'm working with a shopify theme. Sorry for my english.

**Comment by japherwocky** [comment]
We're seeing files downloaded as empty also.

**Comment by jaylinski** [comment]
Same here. `theme watch` does nothing when changing a file. But it spawns the workers:
```
Spawning 2 workers for 
sandovita.myshopify.com Worker #1 ready to upload local changes
sandovita.myshopify.com Worker #0 ready to upload local changes
```

Is there any way to debug the watcher?

#### Version
Theme Kit v0.4.4

#### config.yml:
```
development:
  password: xxx
  theme_id: "xxx"
  store: xxx.myshopify.com
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
  timeout: 30s
  ignore_files:
    - ".idea/*"
    - ".gitignore"
    - ".editorconfig"
```
