### ISSUE TITLE
[401] Insufficient permissions to perform Update

### ISSUE THREAD

**Issue by patdryburgh** [Shopify/themekit#229]
Hello,

I have installed Theme Kit following the instructions found here: http://themekit.cat. I have confirmed that Theme Kit is running with the `theme -h` command.

I've downloaded the theme files and added them to the directory with the `config.yml` file in which I've created a configuration for a development environment environment. 

```
development:
  password: xxxxxxxxxxxxxxxxxxxb04d
  theme_id: xxxxx357
  store: foo.myshopify.com
  timeout: 30s
  ignore_files:
    - config/settings/settings_data.json
    - config/settings.html
```

These are the permissions I've set in the private app:

<img width="643" alt="screen shot 2016-10-13 at 3 12 38 pm" src="https://cloud.githubusercontent.com/assets/751461/19368967/8e50b07c-9157-11e6-839f-36f29a03783a.png">

When running `theme watch` and updating a file, I receive the following error regardless of which file I upload: 

`[401] Insufficient permissions to perform Update to layout/theme.liquid`

I was told to report this issue by a customer support agent. I appreciate your help very much!

—Pat
