### ISSUE TITLE
0.6.2 Windows File Paths are broken in 0.6.2

### ISSUE THREAD

**Issue by tbeseda** [Shopify/themekit#305]
After updating to 0.6.2 on Windows 10 Pro I get the following log entry and an abrupt quit when I run `> theme replace`:
```
08:58:23 [development]Asset config/settings_data.json filtered based on ignore patterns
```
Nothing is logged further and the command quits.

My config looks like:
```
development:
  password: xxxxxxxxxx
  theme_id: "123"
  store: my-fake-store.myshopify.com
  timeout: 120s # helps with big files
  ignore_files:
    - app/
    - node_modules/
    - tmp/
    - Brocfile.js
    - Procfile
    - readme.md
```

I have reverted to 0.6.1 and successfully run `> theme replace`.

I may be able to help troubleshoot in the next few days if you have ideas.

Thanks!
