### ISSUE TITLE
error connecting to myshopify.com

### ISSUE THREAD

**Issue by ryanhca** [Shopify/themekit#311]
I've configured everything according to the instructions in docs. My config.yml file looks like this. 

```
development:
  password: secret
  theme_id: "secret"
  store: myshop.myshopify.com
```
however, I have a redirect that sends users to www.myshop.com and not myshopify.com so I think I'm getting a 404 i.e.;

this error comes up
```
Assets Perform Retrieve at host <myshop.myshopify.com>
	Status: 404 Not Found
	Errors: none
```
I'm wondering if that redirect is throwing off the download of the theme.
