### ISSUE TITLE
Ignores in config.yml not excluded from watch command

### ISSUE THREAD

**Issue by alexborton** [Shopify/themekit#350]
I have setup some ignores (i have tried both` ignore_files` and a link to another file as per the example through `ignores`), but the supposedly ignored files are still updated and uploaded when changed and with a `watch` command running. 

Is this the correct functionality?

**Comment by tanema** [comment]
No this is not correct functionality, Can you please show me your ignores and have you checked the ignores documentation http://shopify.github.io/themekit/ignores/

**Comment by alexborton** [comment]
I have read the documentation and i have to be honest, the use of the hyphen (-) has thrown me a little.

I have tried the following

```
development:
  password: ...
  theme_id: "..."
  store: ....myshopify.com
  ignore_files:
    - config/settings_data.json
```

```
development:
  password: ...
  theme_id: "..."
  store: ....myshopify.com
  ignore_files:
  - config/settings_data.json
```

```
development:
  password: ...
  theme_id: "..."
  store: ....myshopify.com
  ignore_files:
    config/settings_data.json
```
