### ISSUE TITLE
Upload, download, watch hang on 0.6.10

### ISSUE THREAD

**Issue by dictions** [Shopify/themekit#372]
I'm on OSX 10.12.3 and themekit 0.6.10 and I'm not able to get any `upload`, `download`, or `watch` to work.

- I've verified with another team member that the config is correct and works on their machine.
- Verbose mode does not add any additional information.
- Upload and download both hang at 0%. Watch does not detect changes on my file system. 
- I've tried installing themekit via brew, manually, and I've tried the node version. All have the same behavior.

Here is an example of the `config.yml`:

```
---
development:
  theme_id: xxxxxx
  password: xxxxxx
  store: xxxxxx.myshopify.com
  ignore_files:
    - node_modules/
    - dev/
    - .ruby-version
    - .sass-cache/
    - package.json
    - config/settings_data.json
    - config/settings_schema.json
    - Gruntfile.js
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
  timeout: 200s

dev2:
  theme_id: xxxxxx
  password: xxxxxx
  store: xxxxxx.myshopify.com
  ignore_files:
    - node_modules/
    - dev/
    - .ruby-version
    - .sass-cache/
    - package.json
    - config/settings_data.json
    - config/settings_schema.json
    - Gruntfile.js
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
  timeout: 200s
```

**Comment by tanema** [comment]
You have been using themekit a long time! Fist of all you can start by updating your config it should look more like this:

```
development:
  theme_id: xxxxxx
  password: xxxxxx
  store: xxxxxx.myshopify.com
  ignore_files:
    - config/settings_data.json
    - config/settings_schema.json
  timeout: 200s

dev2:
  theme_id: xxxxxx
  password: xxxxxx
  store: xxxxxx.myshopify.com
  ignore_files:
    - config/settings_data.json
    - config/settings_schema.json
  timeout: 200s
```

Next it looks like you have some big files in your project because you have a 200s timeout. Has the command timed out while you are waiting? When you download do you get past the `Fetching asset list from XXX.myshopify.com` message? I would try reinstalling themekit. As a first measure. It soulds like you either have a permissions issue or something has become corrupted in themekit.
