### ISSUE TITLE
Feature Request: "safe" flag for push to live

### ISSUE THREAD

**Issue by rosseSA** [Shopify/themekit#404]
At the moment, it's possible and easy for a tired dev to use the current live theme ID to download the current theme, and forget to change (or incorrectly copy/paste) the theme ID when uploading/watching their changes. ( I haven't actually done this YET, but I'm sure it's possible.)

My proposal is a "safe" mode flag, that checks the ID of the theme set in config is not currently set to "live", or matches the live ID. If the ID is the same as the live theme, then do not allow theme watch or theme upload (either until config change, or by CLI interaction with the user - "Allow upload to live theme? (y/n)".

I'd love to write this feature, but don't know Go, and I'm not realistically going to have the time. 

If anyone thinks this is a good potential feature, or wants to write is as a pull request, I'd be exceptionally grateful. 

R

**Comment by tanema** [comment]
I would suggest not writing your config like that instead. You should probably have a config like this

```
development:
  password: 123
  theme_id: "105994"
  store: can-i-buy-a-feeling.myshopify.com
production:
  password: 123
  theme_id: "live"
  store: can-i-buy-a-feeling.myshopify.com
```

And when you download you would use `theme download --env=production`. This ensures that your live theme is never the default and to edit it at all you would need to specify that environment. The problem with an extra flag is if this theoretical tired dev forgets to change the theme id they will also forget a safe flag.
