### ISSUE TITLE
Theme download config reporting 404 for config files

### ISSUE THREAD

**Issue by mimo84** [Shopify/themekit#444]
### What I expected to happen
performing `theme download --env development config/settings_data.json` returns:
```
error downloading asset: Asset Perform Retrieve to  at host culture-kings-maurizio.myshopify.com
	Status: 404 Not Found
```

If I run:
`theme download --env development` it does download all the theme assets including the files under the config folder. 

### My Environment
OS (including version): OSX 10.12.6 and Ubuntu 16.04
Themekit version: ThemeKit 0.7.2

**Comment by mimo84** [comment]
Investigating the issue further I found how running the `theme config` with multiple configurations is going not to add multiple configurations as it should.

**Comment by mimo84** [comment]
Rolling back to theme kit 0.6.12 seems to fix the issue.
Is it possible to see a changelog?

**Comment by tanema** [comment]
@mimo84 What do you mean 

> I found how running the theme config with multiple configurations is going not to add multiple configurations as it should

Can you provide me with a full command example.

**Comment by mimo84** [comment]
I mean that if I run commands like:
```
theme configure --password=mypassword --store=my-dev-store.myshopify.com --themeid=9999999 --env=dev
```
and:
```
theme configure --password=mypassword --store=my-staging-store.myshopify.com --themeid=9999999 --env=staging
```
the content of my config.yml is:

```
development:
  password: mypassword
  theme_id: "9999999"
  store: my-dev-store.myshopify.com
```
While it should be:
```
development:
  password: mypassword
  theme_id: "9999999"
  store: my-dev-store.myshopify.com
staging:
  password: mypassword
  theme_id: "9999999"
  store: my-staging-store.myshopify.com
```
