### ISSUE TITLE
environment validity check flags repeatable yaml nodes as invalid

### ISSUE THREAD

**Issue by raulmontejo** [Shopify/themekit#446]
This suddenly started happening when I updated from `v0.6.12` to `v0.7.2`. No changes to my config were made.
### What I expected to happen
Specified files upload to my theme.
### What actually happened
`[config] Invalid configuration: missing theme_id`
### Steps to reproduce

1. Define an environment with a `theme_id` in `config.yml`
2. Run the `upload` command with the `--env` or `-e` flag pointing to that environment.

### My Environment

OS (including version): MacOS Sierra 10.12.6 (16G29)
Themekit version: `v0.7.2`
Ignore Files(if any): 
```
ignore_files:
    - src/
    - node_modules/
    - Gulpfile.js
    - package.json
```

**Comment by tanema** [comment]
One of your environments are missing a theme id. It seems like you have a environment called `config` that does not have a theme id. The newest version requires all environments to be valid. Was there more output to this error?

**Comment by raulmontejo** [comment]
@tanema as I said, nothing has changed about my config or the command I'm writing and these worked fine on `v0.6.12`. Perhaps the program is incorrectly searching for an environment by that name `config`, but here's what I'm actually working with...
## My config.yml
.
.
```
production: # LIVE WEBSITE
  theme_id: ********
  readonly: true # safety switch; toggle to deploy
  << : *common
```
.
.
```
config: &common
  password: *********************
  store: storename.myshopify.com
  ignore_files:
    - src/
    - node_modules/
    - Gulpfile.js
    - package.json
```
## Full command & output
```
$ theme upload -e production config/*
14:55:14 [config] Invalid configuration: missing theme_id All environments are required to be valid so that asset versions can be validated
```
and with the flags and files swapped,
```
$ theme upload config/* -e production
14:55:33 [config] Invalid configuration: missing theme_id All environments are required to be valid so that asset versions can be validated
```

**Comment by raulmontejo** [comment]
@tanema looks like the program is treating my map as an environment. Can we loosen the logic there so that doesn't happen?

**Comment by tanema** [comment]
Okay I understand now. I did not design it to handle this re-usable config style. I will have to see if I can figure out a way to allow this. I don't want to just warn the user of invalid configs because it could make the command start uploading/replacing when it couldn't check the manifest properly. I totally understand wanting to use this feature of yaml though since it obviously makes your config a lot more manageable. I will have to see if I can find a way to tell if it is an environment I can skip.

**Comment by neycodes** [comment]
@tanema Thanks for taking our re-usable config setups into account! Please let us know if/when you have a solution.

Here's my config if it helps:

```
SHARED: &SHARED
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "*.swp"
    - "*~"
    - node_modules/
    - src/
    - package.json
    - yarn.lock
    - webpack.config.js
    - README.md

## LIVE theme - DO NOT TOUCH THIS THEME!!!
live:
  <<: *SHARED
  store: STORE_NAME_HERE.myshopify.com ## Live Store name.
  password: ADD_PASSWORD_HERE ## Private App password from Shopify.
  theme_id: 'ADD_THEME_ID_HERE' ## ID number of the store's LIVE theme.

## Staging theme - Push to this theme after your changes have been completed in your theme.
staging:
  <<: *SHARED
  store: STORE_NAME_HERE.myshopify.com ## Staging Store name.
  password: ADD_PASSWORD_HERE ## Private App password from Shopify.
  theme_id: 'ADD_THEME_ID_HERE' ## ID number of the theme you will push your changes to when finished.

## This is your theme on live store.
your-theme-live:
  <<: *SHARED
  store: STORE_NAME_HERE.myshopify.com ## Live Store name.
  password: ADD_PASSWORD_HERE ## Private App password from Shopify.
  theme_id: 'ADD_THEME_ID_HERE' ## ID number of your theme on live store.

## This is your theme on test store. You should make all your changes here and view on test/development store while working.
your-theme-test:
  <<: *SHARED
  store: STORE_NAME_HERE.myshopify.com ## test/development store name.
  password: ADD_PASSWORD_HERE ## Private App password from Shopify.
  theme_id: 'ADD_THEME_ID_HERE' ## ID number of the theme you will make your changes on.

```
