### ISSUE TITLE
YAML error: line 3: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by QuintinS** [Shopify/themekit#526]
I used `theme watch` as normal, but for some reason I receive the following error:

`13:26:45 YAML error: line 3: mapping values are not allowed in this context`

My `config.yml`:

```
development:
  password: 6317987e924c1c255974eee9424011e5
  theme_id: "31926845541"
  store: smallpetselect.myshopify.com
  directory: shop
  ignore_files:
    - config/settings_data.json

deploybot_dev:
  password: 6317987e924c1c255974eee9424011e5
  theme_id: "2391212058"
  store: smallpetselect.myshopify.com
  directory: shop
  ignore_files:
    - config/settings_data.json

live:
  password: 6317987e924c1c255974eee9424011e5
  theme_id: "2404876314"
  store: smallpetselect.myshopify.com
  directory: shop
  ignore_files:
    - config/settings_data.json
  readonly: true
```

Strangely, I checked out a different branch with a different version of `config.yml`, where `theme watch` worked as long as I was on the branch. But if I copy and paste the contents of the working `config.yml` exactly onto my current branch, `theme watch` fails with the same error as above.

The working `config.yml` is:

```
development:
  password: 6317987e924c1c255974eee9424011e5
  theme_id: "31876153445"
  store: smallpetselect.myshopify.com
  directory: shop
  ignore_files:
    - config/settings_data.json

live:
  password: 6317987e924c1c255974eee9424011e5
  theme_id: "2404876314"
  store: smallpetselect.myshopify.com
  directory: shop
  ignore_files:
    - config/settings_data.json
  readonly: true
```

I validated the YAML and it looks fine. What could be wrong?

OS (including version): `MacOS Sierra 10.12.6 (16G1212)`
Themekit version: `0.7.5`
Ignore Files(if any):

```
# Windows image file caches
Thumbs.db
ehthumbs.db

# Folder config file
Desktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msm
*.msp

# Windows shortcuts
*.lnk

# =========================
# Operating System Files
# =========================

# OSX
# =========================

.DS_Store
.AppleDouble
.LSOverride

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk

/node_modules
/shop/config/settings_data.json
/bower_components
theme.lock
```
