### ISSUE TITLE
Get Proxy URL detected from Configuration [http://localhost:3000] SSL Certificate Validation will be disabled! when I run the the theme watch command even I dont have proxy config.

### ISSUE THREAD

**Issue by axlopez12** [Shopify/themekit#561]
### What happened
Got an error when I run the command **theme watch --env=developement** or **theme deploy --nodelete  --env=production** the error says, Proxy URL detected from Configuration [http://localhost:3000] SSL Certificate Validation will be disabled!Get https://ninemonthssober.myshopify.com/meta.json: proxyconnect tcp: dial tcp [::1]:3000: connectex: No connection could be made because the target machine actively refused it.
Even I don't have proxy config on my config.yml.

### What I expected to happen
Properly watch the development theme, without an error.

### Steps to reproduce

1. Run theme watch --env=development

### My Environment

OS (including version): Windows 10 64 bit
Themekit version: v0.8.1-prerelease
Ignore Files(if any):
- todo
- config/settings_data.json

### My Config
```
:api_key: [api key]
:ignore_files:
- todo
- config/settings_data.json
development:
  password: [pw]
  theme_id: [id]
  store: [shopify.com]
production:
 development:
  password: [pw]
  theme_id: [id]
  store: [shopify.com]
  timeout: 60s
```

Thank you very much.
