### ISSUE TITLE
theme deploy updates ignored files

### ISSUE THREAD

**Issue by mattAux** [Shopify/themekit#627]
**config.yml**
Simplified filenames & hid passwords / store names
```
development:
  password: xxxxxxxxxxxx
  theme_id: "xxxxxxxxx"
  store: dev.myshopify.com
  ignore_files:
    - config/settings_data.json
    - snippets/foo-config.liquid
    - snippets/foo.liquid
production:
  password: xxxxxxxxx
  theme_id: "xxxxxxxxx"
  store: live.myshopify.com
  ignore_files:
    - config/settings_data.json
    - snippets/foo-config.liquid
    - snippets/foo.liquid
```

**To Reproduce**
1. add test text to section you wish using shopify -> themes -> customize, which should update settings_data.json on the store ( not local files )
2. run command 'theme deploy' ( in my case - 'theme deploy --env=production' )
3. check test section & it has been over written by the local settings_data.json ( generally outdated )

**Expected behavior**
If a user has updated a section ( live settings_data.json ), using theme deploy should not overwrite the section changes with outdated settings_data.json if it is included in the "ignored_files" in config.yml - where in fact it is not being ignored & the changes made by user are overwritten.

**Environment:**
 - OS: macOS Mojave 10.14.3 & Ubuntu 18.04.1 lts
- Themekit version: ThemeKit 1.0.0 darwin/amd64 & ThemeKit 1.0.0 linux/amd64
 - Editor: Atom & Visual Studio Code

**Additional context**
Essentially, client updated a section. Then I deployed code updates & their changes were overwritten by my deployment even though settings_data.json is "ignored" correctly.
