### ISSUE TITLE
Env variable file not being loaded in Get command

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/themekit#639]
**Describe the bug**

I have a file at ` ~/Library/Application Support/Shopify/Themekit/variables` that looks like this:

```
DEV_PASSWORD=xxxxxxxxxx
DEV_THEMEID=yyyyyyyyy
DEV_SHOP=my-shop-name.myshopify.com

```

And a `config.yml` file in my project/current directory that looks like this:

```
development:
  password: ${DEV_PASSWORD}
  theme_id: ${DEV_THEMEID}
  store: ${DEV_SHOP}
```

But when I try to list my themes I get this:

```
$ theme get --list --env=development
invalid environment [development]: (missing store domain,missing password)
```

I've verified that everything works properly if I hard code the variables into `config.yml`. Am I missing something? 

**To Reproduce**

Create a file at ` ~/Library/Application Support/Shopify/Themekit/variables` that looks like this:

```
DEV_PASSWORD=xxxxxxxxxx
DEV_THEMEID=yyyyyyyyy
DEV_SHOP=my-shop-name.myshopify.com
```

And a `config.yml` file in your project/current directory that looks like this:

```
development:
  password: ${DEV_PASSWORD}
  theme_id: ${DEV_THEMEID}
  store: ${DEV_SHOP}
```

Then try to list you themes:

```
$ theme get --list --env=development
invalid environment [development]: (missing store domain,missing password)
```

**Expected behavior**

Listing the themes should work just the same as if the config variables were hardcoded into `config.yml`.

**Environment (please complete the following information):**
 - OS : macOS 10.13.6
- Themekit version : ThemeKit 1.0.0 darwin/amd64 (Installed via homebrew)
 - Editor : vim
 - Ignore: ??

**Additional context**

N/A
