### ISSUE TITLE
Misleading messages from theme watch

### ISSUE THREAD

**Issue by tms320c** [Shopify/themekit#653]
**Describe the bug**
theme watch reports about files which it is supposed to ignore. The files are not uploaded, just reported.

**To Reproduce**
1. project contains CSS and JS sources (to be compiled) in subdirectories of ./assets directory
2. config.yml contains the directive to ignore that subdirectories (e.g. ignore_files: assets/sass/)
3. theme watch
4. modify a source file (e.g. theme.scss)
5. see "07:47:45 [development] processing assets/sass/theme.scss" and
6. "[development] (assets/sass/theme.scss) Theme files may not be stored in subfolders"

**Expected behavior**
No messages regarding the files/folders which are ignored by configuration.

**Environment (please complete the following information):**
 - Win10
- Themekit version [e.g. v0.7.5]: ThemeKit 1.0.1 windows/amd64
 - Editor [e.g. atom, sublime]: notepad++
 - Ignore: in config.yml

**Additional context**
Config.yml

```
development:
  password: *************************
  theme_id: "********************"
  store: **********.myshopify.com
  ignore_files:
  - .git/
  - node_modules/
  - assets/js/
  - assets/sass/
  - .gitignore
  - package.json
  - yarn.lock
  - webpack.config.js
  - .babelrc
  - .eslintignore
  - .eslintrc.json
  proxy: ************
  timeout: 1m0s
```
