### ISSUE TITLE
ThemeID flag fails to override global variable ThemeId from config.yml

### ISSUE THREAD

**Issue by Christopher-Hayes** [Shopify/themekit#674]
**Describe the bug**
When I try to specify a `themeid` to use instead of the `config.yml` `themeid` using `--themeid [theme id]`, the command still uses the `themeid` from the config. For example, if themeid **XXXXXX** is in my `config.yml`, and I run `theme watch --themeid YYYYYY`, the CLI prints `"Watching for file changes to theme XXXXXX"`.
Not sure if relevant, the config is using a global variable, not a hard-coded theme id.

**To Reproduce**
1. Set up `config.yml` to use the theme_id from a global variable for the default development environment.
```
development:
  theme_id: THEMEKIT_THEME_ID
```
2. Run any command in CLI with a **different** theme id set. For example:
```
theme watch --themeid=12345678910
``` 

**Expected behavior**
The `theme watch` should watch the theme specified. The CLI output should specify it is watch the theme `12345678910`.
`"Watching for file changes to theme 12345678910"`.

**Actual behavior**
If 99999999999 was the themeid in the `config.yml`, the execution of `theme watch --themeid=12345678910` would result in the CLI output `"Watching for file changes to theme 99999999999"`. I assuming this CLI print can be trusted, I have not actually tested if it watches the `config.yml` theme or the theme specified in the CLI.

![image](https://user-images.githubusercontent.com/6013871/71527250-98b77c80-28a8-11ea-8f59-8d6427d1da65.png)

**Environment:**
 - Windows 10 Pro (1909)
- ThemeKit 1.0.3 windows/amd64
- MINGW64

**Additional context**
Config uses global variables. Full `config.yml` is below. Only store name is redacted, rest is untouched.
```
SHARED: &SHARED
  store: [REDACTED].myshopify.com
  password: THEMEKIT_PASSWORD
  timeout: 60s
  directory: src/
  ignore_files:
    - "*.swp"
    - "*~"
    - node_modules/
    - package.json
    - README.md

development:
  <<: *SHARED
  theme_id: THEMEKIT_THEME_ID

qa_staging:
  <<: *SHARED
  theme_id: "secret"

production:
  <<: *SHARED
  theme_id: "secret"

```

**Comment by Christopher-Hayes** [comment]
**Temp Fix**

Set the global variable for just a single command.

![image](https://user-images.githubusercontent.com/6013871/71527393-3f9c1880-28a9-11ea-9c6c-c408d6788f33.png)

**Comment by tanema** [comment]
that is interesting! I will have to look into this because the precedence is ENV, flag, config. The Env var works but not the flag. 🤔

**Comment by tanema** [comment]
Okay sorry I dont think I thought this one through when I answered it. This is actually how it is supposed to work. As I said in the last comment, the precedence is ENV > flag > config. That is because it is seen that flags can override your config and environment variables are a set environment that you work in. It is thought that the environment is firm since it is generally the harder approach to setting variables and more firm (especially if setup in something like your bashrc)

Honestly, I didn't imagine people using it for themeids either. I added that feature so that people could add the settings that were common across projects like store domain, api key/secret, and ignore_files. 

I would actually love to know the reason why you put your id as an environment variable instead of a config variable. Could it be that you should be using shared config instead like this?:

```
development:
  <<: *shared
  theme_id: "37660622904"
production:
  <<: *shared
  theme_id: "510918681"
shared: &shared
  password: jkhdskfhsdlkj1298lj;sdfjlksdf1
  store: can-i-buy-a-feeling.myshopify.com
  ignore_files:
    - assets/sass/
```
