### ISSUE TITLE
`deploy` command overrides production theme when `theme_id` is not present or missed spelled

### ISSUE THREAD

**Issue by wizardlyhel** [Shopify/themekit#699]
**Describe the bug**
When the `theme_id` is not present in the `config.yml`, themekit did not fail command and instead push directly onto production theme. There is a warning about updating to live theme but it is way to late to stop the process if it is not intentional.

**To Reproduce**
Note: Using `node-themekit`

1. Have your config.yml setup like the following:
```
development:
  password: [your-api-password]
  thene_id: "[your-theme-id]"                 // Notice the mis-spelled word "thene"
  store: [your-store].myshopify.com
```
2. Run `themekit deploy`

> [development] Warning, this is the live theme on Store.
> [development] 77|183 [================>-----------------------------]  42 %

**Expected behavior**
Default: A confirmation to deploy to production theme before proceeding
With flag: (ie. `--force`) Deploys to production without confirmation

**Environment (please complete the following information):**
- Themekit version [e.g. v0.7.5]: node-themekit "@shopify/themekit": "^1.1.3"
 - Editor [e.g. atom, sublime]: VSCode
