### ISSUE TITLE
Using live theme id as default when another environment was specified can be dangerous

### ISSUE THREAD

**Issue by mizurnix** [Shopify/themekit#752]
### Problem
I think treating live theme as the default during `deploy`, especially when another environment is explicitly specified is both counter-intuitive and dangerous, at least with a setup similar to mine.

This is my config.yml:
```yaml
default: &default
  password: ${THEMEKIT_PASSWORD}
  store: ${THEMEKIT_STORE}
  ignore_files:
  - config/settings_data.json
development:
  <<: *default
  theme_id: ${THEMEKIT_DEV_THEME_ID}
staging:
  <<: *default
  theme_id: ${THEMEKIT_STAGING_THEME_ID}
production:
  <<: *default
  theme_id: ${THEMEKIT_PROD_THEME_ID}
```

When I run `theme deploy`, it deploys to my development theme. When I want to deploy to staging or production, I indicate the environment. For example `theme deploy --env=staging`.

This all works fine when all those environment variables are defined. But if the theme_id variable is not available (for any reason: variable file gone, new developer on the team with incomplete setup, you name it), any kind of deploy is in fact a production deploy. The console gives a warning but it's not a prompt or anything to confirm, it just goes straight at it.

This can result in incomplete work published on the live theme which can cause a big trouble in certain cases.

### Potential solution
I think it would be best to throw an error because theme_id was not found in the specified environment.

If my setup looks like an outlier and changing the default behaviour to suit it sounds like too much, maybe there should be a way to at least disable current approach from `config.yml`.
