### ISSUE TITLE
ignore_files not working with directories in paths (on Windows)

### ISSUE THREAD

**Issue by PhilSole** [Shopify/themekit#797]
**Describe the bug**
I'm using config.yml like so:

```
development:
  password: 12345
  theme_id: "112344939"
  store: ashop.myshopify.com
  ignore_files:
    - settings_data.json
```

That is successfully ignoring settings_data.json but when I have:

```
development:
  password: 12345
  theme_id: "112344939"
  store: ashop.myshopify.com
  ignore_files:
    - config/settings_data.json
```
The settings_data.json file is not being ignored and is getting updated on the remote theme.

**To Reproduce**
1. Using the live theme
2. theme watch --allow-live

**Environment (please complete the following information):**
 - Windows 10
- ThemeKit 1.1.1 windows/amd64
 - Editor VS code
 - Ignore:

**Additional context**
Just set up theme kit.
