### ISSUE TITLE
ThemeKit deploy wants to remove generated file `application.css`

### ISSUE THREAD

**Issue by hinogi** [Shopify/themekit#924]
**Describe the bug**
My `config.yml`:
```
development:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${DEVELOPMENT_THEME_ID}
  store: ${SHOPIFY_SHOP_URL}
  ignores:
  - .themekit_ignores
```
they are no asset files in themekit ignore

Running build step with tailwind:
```
tailwindcss build ./src/css/application.css -o ./assets/application.css.liquid --env production

  
   tailwindcss 1.9.6
  
   🚀 Building: src/css/application.css
  
   ✅ Finished in 3.13 s
   📦 Size: 5.38MB
   💾 Saved to assets/application.css.liquid
```
Running deploy with themekit 1.1.6 `theme deploy -e development -v` :
```
[development] Errors encountered: 
        [development] (assets/application.css) this file is critical and removing it would cause your theme to become non-functional
finished command with errors
```

**To Reproduce**
1. run command `tailwindcss build ./src/css/application.css -o ./assets/application.css.liquid --env production`
2. run command `theme deploy -e development -v`

**Expected behavior**
Deploy the theme and generate application.css.

**Environment (please complete the following information):**
 - Window 10 WSL
 - ThemeKit 1.1.6 linux/amd64
