### ISSUE TITLE
Error downloading config/settings_data.json

### ISSUE THREAD

**Issue by slauzinho** [Shopify/themekit#964]
**Describe the bug**
Themekit gives an error when trying to download `config/settings_data.json`

```
 Errors encountered: 
        [production] error downloading config/settings_data.json: request failed after 5 retries with error: Get https:/XXXXXXXXX.myshopify.com/admin/api/unstable/themes/XXXXXXXXX/assets.json?asset%5Bkey%5D=config%2Fsettings_data.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**To Reproduce**
1. run command 'theme download --password=mypassword --store=store.myshopify.com --name=theme'

**Expected behavior**
I expected to download all the theme files, including the `settings_data`

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MAC OS Catalina
- Themekit version (run theme version to check): 1.3.0
 - Editor [e.g. atom, sublime]: VSCode
- config.yml:

```yml
production:
  password: XXXXXXXXXXXXXXXXXXXXXXXXX
  theme_id: XXXXXXXXXXXXXXXXXXXXX
  timeout: 4000s
  store: XXXXXXXXXXX.myshopify.com
  ignores: -themekit.ignores
```
 - Ignore:
```
# These folders should always be ignored when uploading to shopify
build/
scripts/
styles/
node_modules/
*.lock
*.md
*.yml
*.sh
*.log
*.ignores
.*
```

**Additional context**
This was working fine 2 weeks ago and suddenly it stopped working. Issue seems to be happening for every developer on the team, so it's not a user issue.
I also tried adjusting the timeout value with no success.
