### ISSUE TITLE
Error in config if there's double indentation

### ISSUE THREAD

**Issue by Curzey** [Shopify/themekit#966]
**Describe the bug**
`config.yml` does not respect `ignore_files` settings if the respective file or path starts with extra indentation.

**To Reproduce**
1.  Go to your projects' `config.yml` and find one of the themes' `ignore_files` entry (or add it).

2. Add extra spacing (tabs/spaces) before the dash "-".

It should now look something like this.
```yaml
...
test-development:
  password: [password]
  theme_id: [id]
  store: [store-name].myshopify.com
  ignore_files:
    - config/settings_data.json
      - /locales/* # note the extra spaces before this line
```
3. Make a change in any of your locale files

4. Run `theme deploy --env="test-development"` 

_The change is now updated on the respective theme_

**Expected behavior**
I would expect this to either:

- Just work, ignore the locales changes - it's explicitly defined in `ignore_files`
- Throw an error and do nothing

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac OS Monterey 12.1
- Themekit version (run theme version to check): ThemeKit 1.3.0 darwin/amd64
 - Editor [e.g. atom, sublime]: VS Code
 - Ignore: 

**Additional context**
Has been tested on both M1 and Intel macs
